### ISSUE TITLE
[Feat]the IP address of SBA service should be reported automatically to NRF, for deployment on the kubernetes cloud platform

### ISSUE THREAD

**Issue by mazengxie** [free5gc/free5gc#121]
**If the design issue template is not followed, the issue might be closed.**

### What's the version are you using

v3.0.4

### Is your feature request related to a problem? Please describe.

When free5gc is deployed on the cloud platform, the IP address of the NF is automatically assigned。So, it is very inflexible if we must write it in Configuration file in advance.
In the main microservice frameworks,  the microservice's IP are all automatically registered with Service Discovery Center. For example，SpringCloud Eureka. 

### Describe the solution you'd like
1. Modify SBA service(NFs) listen on "0.0.0.0:port" , that is, "(sbi.IPv4Addr, sbi.Port)" ====> "0.0.0.0:port".
2. If “sbi” is configured in the file, the configuration file has higher priority.

### Describe alternatives/workarounds you've considered

None.

### Additional context
None.

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by endrigoshi** [comment]
Hi @mazengxie ,
I believe this feature is already implemented.
All you need to do is define an ENV containing the IP of the Pod and pass it to the the container configuration file (MY_POD_IP).
```yaml
env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```
Then you define the NF config file as follows:
``` yaml
sbi:
    scheme: http
    registerIPv4: amf-np.free5gc.svc.cluster.local
    bindingIPv4: MY_POD_IP
    port: 29518
```
