### ISSUE TITLE
Running webui in kubernetes

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#43]
Hi,

I am trying to build the webui container image, below is the Dockerfile:

```
FROM golang:1.12.9

WORKDIR /root/

RUN apt update -y && apt -y install git

WORKDIR $GOPATH/src
RUN git clone https://github.com/free5gc/free5gc.git

WORKDIR $GOPATH/src/free5gc/

RUN git submodule update --init && cd webconsole && go get -d -v ./...

CMD ["go", "run", "webconsole/server.go"]
```

But I am getting errors about missing dependencies when I try to run it (I am using k8s):

```
lib/openapi/models/model_access_token_claims.go:12:8: cannot find package "github.com/dgrijalva/jwt-go" in any of:
        /usr/local/go/src/github.com/dgrijalva/jwt-go (from $GOROOT)
        /go/src/github.com/dgrijalva/jwt-go (from $GOPATH)
lib/MongoDBLibrary/api_mongoDB.go:9:2: cannot find package "github.com/evanphx/json-patch" in any of:
        /usr/local/go/src/github.com/evanphx/json-patch (from $GOROOT)
        /go/src/github.com/evanphx/json-patch (from $GOPATH)
webconsole/backend/webui_service/webui_init.go:6:2: cannot find package "github.com/gin-contrib/cors" in any of:
        /usr/local/go/src/github.com/gin-contrib/cors (from $GOROOT)
        /go/src/github.com/gin-contrib/cors (from $GOPATH)
webconsole/backend/WebUI/api_webui.go:15:2: cannot find package "github.com/gin-gonic/gin" in any of:
        /usr/local/go/src/github.com/gin-gonic/gin (from $GOROOT)
        /go/src/github.com/gin-gonic/gin (from $GOPATH)
webconsole/backend/webui_context/context.go:5:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
        /usr/local/go/src/github.com/mitchellh/mapstructure (from $GOROOT)
        /go/src/github.com/mitchellh/mapstructure (from $GOPATH)
lib/CommonConsumerTestData/logger/logger.go:5:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
        /go/src/github.com/sirupsen/logrus (from $GOPATH)
src/app/init.go:6:2: cannot find package "github.com/urfave/cli" in any of:
        /usr/local/go/src/github.com/urfave/cli (from $GOROOT)
        /go/src/github.com/urfave/cli (from $GOPATH)
lib/MongoDBLibrary/api_mongoDB.go:10:2: cannot find package "go.mongodb.org/mongo-driver/bson" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/bson (from $GOROOT)
        /go/src/go.mongodb.org/mongo-driver/bson (from $GOPATH)
lib/MongoDBLibrary/api_mongoDB.go:11:2: cannot find package "go.mongodb.org/mongo-driver/mongo" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/mongo (from $GOROOT)
        /go/src/go.mongodb.org/mongo-driver/mongo (from $GOPATH)
lib/MongoDBLibrary/api_mongoDB.go:12:2: cannot find package "go.mongodb.org/mongo-driver/mongo/options" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/mongo/options (from $GOROOT)
        /go/src/go.mongodb.org/mongo-driver/mongo/options (from $GOPATH)
src/udr/factory/factory.go:11:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
        /go/src/gopkg.in/yaml.v2 (from $GOPATH)
src/app/context.go:7:2: cannot find package "gopkg.in/yaml.v3" in any of:
        /usr/local/go/src/gopkg.in/yaml.v3 (from $GOROOT)
        /go/src/gopkg.in/yaml.v3 (from $GOPATH)
```

Any idea on how to fix the Dockerfile? 

Also what are the configuration parameters that is needed to run this especially in a k8s environment, below is the deployment manifest I will use:

```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:      
      - name: free5gc-webui-container
        image: registry.gitlab.com/infinitydon/registry/free5gc-webui:v3.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
---
kind: Service
apiVersion: v1
metadata:
  name: free5gc-webui-service
spec:
  selector:
    app: free5gc-webui
  ports:
  - protocol: TCP
    port: 5000            
```
