### ISSUE TITLE
INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN

### ISSUE THREAD

**Issue by Usman5376855** [free5gc/free5gc#542]
```
[2024-03-12 07:56:10.732] [nas] [info] Initial Registration is successful
[2024-03-12 07:56:10.732] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:10.732] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:10.952] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:11.792] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:11.792] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:11.813] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:12.893] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:12.893] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:12.910] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:13.994] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:13.994] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:14.010] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:15.095] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:15.095] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:15.114] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:16.196] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:16.196] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:16.214] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:17.297] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:17.297] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:17.314] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
[2024-03-12 07:56:18.398] [nas] [debug] Sending PDU Session Establishment Request
[2024-03-12 07:56:18.398] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2024-03-12 07:56:18.417] [nas] [error] PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
```

**Comment by tim1207** [comment]
Hello,

PDU Session Establishment Reject received [INSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN]
This cause is usually rejected by SMF because the UPF is not running.
Please send us the SMF log, then we can check it.

**Comment by Usman5376855** [comment]
Hi There ,

I am still observing this "NSUFFICIENT_RESOURCES_FOR_SPECIFIC_SLICE_AND_DNN" 

SMF logs and UPF logs are pasted below 

 ```yaml
////SMF Logs
ubuntu@ubuntu:~/free5gc/config$ cat smfcfg.yaml
info:
  version: 1.0.7
  description: SMF initial local configuration

configuration:
  smfName: SMF # the name of this SMF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.2 # IP used to register to NRF
    bindingIPv4: 127.0.0.2 # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      key: cert/smf.key # SMF TLS Certificate
      pem: cert/smf.pem # SMF TLS Private key
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
    - nsmf-pdusession # Nsmf_PDUSession service
    - nsmf-event-exposure # Nsmf_EventExposure service
    - nsmf-oam # OAM service
  snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Informat                                                                                                             ion) list supported by this AMF
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFF                                                                                                             FFF)
      dnnInfos: # DNN information list
        - dnn: internet # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFF                                                                                                             FFF)
      dnnInfos: # DNN information list
        - dnn: internet # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
  plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove th                                                                                                             is key when unnecessary)
    - mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs a                                                                                                             re located
  pfcp: # the IP address of N4 interface on this SMF (PFCP)
    # addr config is deprecated in smf config v1.0.3, please use the following c                                                                                                             onfig
    nodeID: 127.0.0.1 # the Node ID of this SMF
    listenAddr: 127.0.0.1 # the IP/FQDN of N4 interface on this SMF (PFCP)
    externalAddr: 127.0.0.1 # the IP/FQDN of N4 interface on this SMF (PFCP)
  userplaneInformation: # list of userplane information
    upNodes: # information of userplane node (AN or UPF)
      gNB1: # the name of the node
        type: AN # the type of the node (AN or UPF)
      UPF: # the name of the node
        type: UPF # the type of the node (AN or UPF)
        nodeID: 127.0.0.8 # the Node ID of this UPF
        addr: 127.0.0.8 # the IP/FQDN of N4 interface on this UPF (PFCP)
        sNssaiUpfInfos: # S-NSSAI information list for this UPF
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Informa                                                                                                             tion)
              sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 010203 # Slice Differentiator (3 bytes hex string, range: 0000                                                                                                             00~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: internet
                pools:
                  - cidr: 10.60.0.0/16
                staticPools:
                  - cidr: 10.60.100.0/24
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Informa                                                                                                             tion)
              sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 112233 # Slice Differentiator (3 bytes hex string, range: 0000                                                                                                             00~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: internet
                pools:
                  - cidr: 10.61.0.0/16
                staticPools:
                  - cidr: 10.61.100.0/24
        interfaces: # Interface list for this UPF
          - interfaceType: N3 # the type of the interface (N3 or N9)
            endpoints: # the IP address of this N3/N9 interface on this UPF
              - 172.27.129.34 # 127.0.0.8
            networkInstances:  # Data Network Name (DNN)
              - internet
    links: # the topology graph of userplane, A and B represent the two nodes of                                                                                                              each link
      - A: gNB1
        B: UPF
  # retransmission timer for pdu session modification command
  t3591:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  # retransmission timer for pdu session release command
  t3592:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  #urrPeriod: 10 # default usage report period in seconds
  #urrThreshold: 1000 # default usage report threshold in bytes

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error,                                                                                                              fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
ubuntu@ubuntu:~/free5gc/config$

////
UPF Logs

ubuntu@ubuntu:~/free5gc/config$ cat upfcfg.yaml
version: 1.0.3
description: UPF initial local configuration

# The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
pfcp:
  addr: 127.0.0.8   # IP addr for listening
  nodeID: 127.0.0.8 # External IP or FQDN can be reached
  retransTimeout: 1s # retransmission timeout
  maxRetrans: 3 # the max number of retransmission

gtpu:
  forwarder: gtp5g
  # The IP list of the N3/N9 interfaces on this UPF
  # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
  ifList:
    - addr: 172.27.129.34 # 127.0.0.8
      type: N3
      # name: upf.5gc.nctu.me
      # ifname: gtpif
      # mtu: 1400

# The DNN list supported by UPF
dnnList:
  - dnn: internet # Data Network Name
    cidr: 10.60.0.0/24 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
    # natifname: eth0

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
ubuntu@ubuntu:~/free5gc/config$


//Below logs shows that UPF is working right ?  I have followed this step #[C. Install User Plane Function (UPF)](https://free5gc.org/guide/3-install-free5gc/#c-install-user-plane-function-upf) " during free5gc installation 
```
