### ISSUE TITLE
Duplicate Definition of t3555 Timer in amfcfg.yaml

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#547]
According to the URL below (free5gc v3.4.0), t3555 is defined twice:
https://github.com/free5gc/free5gc/blob/main/config/amfcfg.yaml

I believe it is incorrect to describe the same timer in two places.
What should be the correct definition for this?

```
 # retransmission timer for NAS Configuration Update Command message
  t3555:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
     :　：
  # retransmission timer for Configuration Update Command message
  t3555:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
```
