### ISSUE TITLE
[Bugs] SMF panic on external (3rd party) CHF integration

### ISSUE THREAD

**Issue by losdrugi** [free5gc/free5gc#562]
## Describe the bug
I'm trying to configure Free5gc to use CHF from the external provider. I succesfuly registered this CHF in NRF, but when I try to connect UE, the following errors occur (full logs also attached): 

SMF:
2024-04-29T16:59:34.312541475+02:00 [INFO][SMF][PduSess] CHF Selection for SMContext SUPI[imsi-208930000000001] PDUSessionID[2]
2024-04-29T16:59:34.315972245+02:00 [INFO][SMF][Charging] Handle SendConvergedChargingRequest
2024-04-29T16:59:34.316362270+02:00 [ERRO][SMF][GIN] [Debugging] panic:
POST /nsmf-pdusession/v1/sm-contexts HTTP/2.0
(...callstack...)
2024-04-29T16:59:34.316934563+02:00 [INFO][SMF][GIN] | 500 |       127.0.0.1 | POST    | /nsmf-pdusession/v1/sm-contexts |

AMF:
2024-04-29T16:59:34.192410890+02:00 [DEBU][AMF][Gmm][amf_ue_ngap_id:RU:1,AU:1(3GPP)][supi:SUPI:imsi-208930000000001] Search SMF from NRF[http://192.168.16.130:8000]
2024-04-29T16:59:34.256748241+02:00 [ERRO][AMF][Gmm][amf_ue_ngap_id:RU:1,AU:1(3GPP)][supi:SUPI:imsi-208930000000001] CreateSmContextRequest Error: undefined response type

This only happens with an external CHF, when Free5gc CHF is used, everything works ok. 

Except NRF registartion request and watchdog requests I see no other communication between external CHF and Free5gc, so I think the issue is not related to the external CHF response format or behaviour. 

## To Reproduce
1. start Free5gc modules, except of Free5gc-CHF (those are started on VM1: 192.168.16.130)
2. start external CHF (started on VM2: 192.168.16.129). CHF is succesfuly registared in NRF
3. start gNB (UERANSIM on VM2)
4. start UE (UERANSIM on VM2) - this step causes described internal errors on F5gc side.

## Environment (please complete the following information):
 - free5GC Version: v3.4.1
 - OS: Ubuntu Ubuntu 22.04.4 LTS (VM)
 - Kernel version: 6.5.0-28-generic
 - go version: go1.18.1 linux/amd64
 - c compiler version (Option): gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Configuration File
[config_e500.zip](https://github.com/free5gc/free5gc/files/15150191/config_e500.zip)

### PCAP File
[trace.zip](https://github.com/free5gc/free5gc/files/15150219/trace.zip)

### Log File
[amf.log](https://github.com/free5gc/free5gc/files/15150190/amf.log)
[smf.log](https://github.com/free5gc/free5gc/files/15150192/smf.log)

**Comment by andy89923** [comment]
Could you provide which CHF you are using?

**Comment by losdrugi** [comment]
Commercial CHF from Comarch (https://www.comarch.com/telecommunications/bss-solutions/convergent-billing-system/) so not so easily available from outside (but if really needed, I could try to expose it to the external network).

**Comment by losdrugi** [comment]
I just found a valid testcase, that does not require any 3rd party software :-) You just need to fun Free5gc CHF on a separate host (VM). 

Steps to reproduce: 
1. Start Free5gc modules on VM1, except of CHF and Webconsole
2. Configure Webconsole and CHF onf VM2 - the only configuration change is to set NRF address pointing NFR@VM1
3. Start Webconsole and set the same SIM configuration as on VM1
4. Start CHF => this step throws an error on SMF:

2024-04-30T11:08:59.151342404+02:00 [INFO][SMF][PduSess] CHF Selection for SMContext SUPI[imsi-208930000000001] PDUSessionID[2]
2024-04-30T11:08:59.155172041+02:00 [INFO][SMF][Charging] Handle SendConvergedChargingRequest
2024-04-30T11:08:59.155463327+02:00 [ERRO][SMF][GIN] [Debugging] panic:
POST /nsmf-pdusession/v1/sm-contexts HTTP/2.0
Host: 127.0.0.2:8000
Accept: application/json
Accept-Encoding: gzip
Content-Length: 804
Content-Type: multipart/related; boundary="ed717142afaec39c3c12a321413b55e3fb820a2f64b850724f833917efb1"
User-Agent: OpenAPI-Generator/1.0.0/go


runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
runtime/debug.Stack()
	/usr/lib/go-1.18/src/runtime/debug/stack.go:24 +0x65
github.com/free5gc/util/logger.ginRecover.func1.1()
	/home/f5gc/go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:284 +0x1a5
panic({0xb4de20, 0x11ac2f0})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
github.com/free5gc/smf/internal/sbi/consumer.SendConvergedChargingRequest(0xc00053b600, 0x0, {0x0, 0x0, 0x0})
	/home/f5gc/free5gc/NFs/smf/internal/sbi/consumer/converged_charging.go:94 +0x4e6
github.com/free5gc/smf/internal/sbi/producer.CreateChargingSession(0xc00053b600?)
	/home/f5gc/free5gc/NFs/smf/internal/sbi/producer/charging_trigger.go:16 +0x26
github.com/free5gc/smf/internal/sbi/producer.HandlePDUSessionSMContextCreate(0x0, {0xc00053fb00, {0xc000129800, 0x15, 0x3e8}})
	/home/f5gc/free5gc/NFs/smf/internal/sbi/producer/pdu_session.go:197 +0x1427

**Comment by andy89923** [comment]
> 2. Configure Webconsole and CHF on VM2 - the only configuration change is to set NRF address pointing NRF@VM1

Another thing that has to be configured is `MongoDB`. You have to change the MongoDB URL in `chfcfg.yaml`. 
To the Mongo server, where is your VM1.  

```yaml
configuration:
  chfName: CHF # the name of this CHF
  sbi: # Service-based interface information
  nrfUri: http://192.168.16.130:8000 # a valid URI of NRF
  mongodb: # the mongodb connected by this CHF
    name: free5gc # name of the mongodb
    url: mongodb://localhost:27017 # a valid URL of the mongodb
```

However, I am still determining if this would solve the problem, but I will get back to you ASAP.

**Comment by andy89923** [comment]
In our Charging design, the `ratingGroup` will be allocated to each PDU Session in PCF, and written back to MongoDB. 
CHF would use `ratingGroup` from DB to calculate the usage and do some work.... 

I am checking the spec whether this procedure follows the rule.

**Comment by losdrugi** [comment]
In my CHF rating groups must be directly configured. When we integrate CHF with customer network, we must agree rating group IDs that will be provided from the network and prepare configuration on our side (e.g. different charging rules per each RG). On the same way we need to provision SIM data for ech SIM card registered in customer network directly to CHF. If Free5gc CHF shares database with other network components it is a problem in real-life scenarios, where the network uses components from different vendors. 

So for the target solution I think there should be a place in Free5GC configuration (GUI) where you can directly define rating group configuration (or at least display RGs automaticaly configured by F5GC). In this case I'd configure the same RG IDs in CHF with dedicated charging configurations per each group). 

For now - is there any workaround possible? E.g. can I somehow directly insert those RGs to MongoDB?

**Comment by andy89923** [comment]
The rating group would be allocated by the PCF when the PDU Establishment procedure and the PCF would write the rating group to MongoDB. So, there is no way you want to use the rating group from MongoDB if you don't change the code in PCF.

However, your point about "there should be a place to define rating group directly" is correct. 
We would consider and discuss how to implement or refactor the mechanism for allocating rating group.

**Comment by losdrugi** [comment]
Can you please decribe in more details how it works currently? 

I assumed that it works this way: 

1. When you configure new SIM in Webconsole, you define network slices and flow rules for this SIM. I think this maps directly to RG configuration. This data is important For PCF, to know which RG shoud be assigned (based on which network slice & IP is used by SIM) and for CHF, to know which charging data (online/offline, quota, unit cost) should be used for a given RG. This data is stored in MongoDB
2. When SIM connects to the network, PCF allocates RG (it uses MongoDB data for this)
3. After RG is allocated, SMF should ask CHF for charging (directly through SBI/N40)
4. CHF should recieve charging requst (SBI/N40) with the information which RG ID is used by SIM
5. CHF should perform charging (based on data from CHF-side MongoDB) and reply to SMF through the same interface 

At this moment I don't understand, why SMF crashes before sending any data to external CHF (if only SBI should be used between those components). So can you please clarify how it is implemented currently?

**Comment by andy89923** [comment]
I looked deep into the log you provided from the first message; I didn't see that CHF registered to NRF. 
So SMF can't find the CHF from NRF, which causes panic. (That is the SMF bug, which didn't check whether the CHF is nil or not). 
Could you provide the external CHF config?

**Comment by losdrugi** [comment]
Please check the trace I attached for HTTP at port 8000. This is our misconfiguration that our CHF uses HTTP instead of HTTP/2 for NRF registration. But besides of that communication looks correct. CHF issues bootstrap message (which is not recognized by your NRF, as this is from Rel 17 (not supported on your side yet), but later it starts normal registration, that is completed with success (also we set an annoying 1s watchdog which also is correctly supported by NRF, so later we have PATCH watchdog requests each second ;-) ). See attached screen:

![image](https://github.com/free5gc/free5gc/assets/77122656/e4c69316-89ee-4df6-be04-91d8e4adc44a)

But as I wrote in my post (Apr 30) - the same issue can be reproduced with Free5gc CHF installed on separate VM (along with the second instance of Webconsole - to create te same SIM config in MongoDB).

**Comment by andy89923** [comment]
Could you provide the CHF config?
The one you use in VM2 and our CHF.

**Comment by losdrugi** [comment]
[chfcfg.zip](https://github.com/free5gc/free5gc/files/15218716/chfcfg.zip)

Nothing interesting there - only SBI and NRF IP addresses changed.

**Comment by andy89923** [comment]
I didn't see where is this packet, is it from another pcap file? 
 
> ![image](https://private-user-images.githubusercontent.com/77122656/328123253-e4c69316-89ee-4df6-be04-91d8e4adc44a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODY2MjcsIm5iZiI6MTcxNDk4NjMyNywicGF0aCI6Ii83NzEyMjY1Ni8zMjgxMjMyNTMtZTRjNjkzMTYtODllZS00ZGY2LWJlMDQtOTFkOGU0YWRjNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5MDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODYzN2JjMWMxNGNmOTcwNTkzYzE5M2ViMTQ5YTRlNjY0OTc3N2I2NjY5ZTc4YjcwMmIyNTYyNzM0M2RhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYo8iRQvjHNcKVcllADvnrdoKYksspGJ_X5FDYqx1zU)
>

**Comment by losdrugi** [comment]
Those packets are filtered directly from [trace.zip](https://github.com/free5gc/free5gc/files/15150219/trace.zip) that was attached to my first post here. Maybe you need to change decoding manualy in Wireshark: 

![image](https://github.com/free5gc/free5gc/assets/77122656/b1c46af6-d615-435d-8acf-8c68de47a4f7)

**Comment by andy89923** [comment]
Thanks for the reminder. I forgot to adjust the decode setting in Wireshark. 


I discovered that the NFProfile from external CHF didn't contain `apiPrefix` in `nfServices.` 
![chf](https://github.com/free5gc/free5gc/assets/28786462/a39d8fc8-d880-4f97-b8bc-7b8f8c230954)
And this is the sample NfProfile (PCF):
![pcf](https://github.com/free5gc/free5gc/assets/28786462/75093bc3-67d7-4f1d-8891-a22b7983833c)

And the SMF would use `apiPrefix` to construct the client. 
https://github.com/free5gc/smf/blob/bd173ab08579b3a060f619b0b300114e2f46dce8/internal/context/sm_context.go#L516C1-L516C2 
```go
	// Create Converged Charging Client for this SM Context
	for _, service := range *smContext.SelectedCHFProfile.NfServices {
		if service.ServiceName == models.ServiceName_NCHF_CONVERGEDCHARGING {
			ConvergedChargingConf := Nchf_ConvergedCharging.NewConfiguration()
			ConvergedChargingConf.SetBasePath(service.ApiPrefix)
			smContext.ChargingClient = Nchf_ConvergedCharging.NewAPIClient(ConvergedChargingConf)
		}
	}
```
These cause the SMF panic when connect with external CHF.

**Comment by andy89923** [comment]
I haven't tried to reproduce the use of our CHF in another VM, whether it would lead to the same question you have mentioned.
Do you have the PCAP file for this scenario?

**Comment by losdrugi** [comment]
Ok, I'll check this apiPrefix. But this does not explain crash with Free5gc CHF. I'll try to reproduce it once more with your CHF and attach all logs/traces.

**Comment by losdrugi** [comment]
Here are logs and traces from the test with Free5gs CHF running on second VM: 

[20240506.zip](https://github.com/free5gc/free5gc/files/15222443/20240506.zip)

I see that apiPrefix is set correctly by CHF: 

![image](https://github.com/free5gc/free5gc/assets/77122656/fa6cbf19-1914-42be-b9d0-f66e2d59893b)

But there is still the same crash on SMF side (see attached logs). 

Tomorrow we'll try to add apiPrefix to our CHF, but it seems like this does not solve the issue...

**Comment by andy89923** [comment]
I tried to run our CHF on another VM, and everything work normally without any panic. 
Here is my CHF config:
```yaml
info:
  version: 1.0.3
  description: CHF initial local configuration

configuration:
  chfName: CHF # the name of this CHF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: <VM2> # IP used to register to NRF
    bindingIPv4: <VM2> # IP used to bind the service
    port: 8000 # port used to bind the service
    tls: # the local path of TLS key
      pem: cert/chf.pem # CHF TLS Certificate
      key: cert/chf.key # CHF TLS Private key
  nrfUri: http://<VM1>:8000 # a valid URI of NRF
  nrfCertPem: cert/nrf.pem # NRF Certificate
  serviceNameList: # the SBI services provided by this CHF, refer to TS 32.291
    - nchf-convergedcharging # Nchf_AMPolicyControl service
  mongodb: # the mongodb connected by this CHF
    name: free5gc # name of the mongodb
    url: mongodb://<VM1>:27017 # a valid URL of the mongodb
  quotaValidityTime: 10000
  volumeLimit: 50000
  volumeLimitPDU: 10000
  volumeThresholdRate: 0.8
  cgf:
    hostIPv4: <VM1>
    port: 2122
    listenPort: 2121
    tls:
      pem: cert/chf.pem
      key: cert/chf.key
    cdrFilePath: /tmp
  abmfDiameter:
    protocol: tcp
    hostIPv4: 127.0.0.113
    port: 3868
    tls:
      pem: cert/chf.pem
      key: cert/chf.key
  rfDiameter:
    protocol: tcp
    hostIPv4: 127.0.0.113
    port: 3869
    tls:
      pem: cert/chf.pem # CHF TLS Certificate
      key: cert/chf.key # CHF TLS Private key
logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
```
VM1 runs all NFs (without CHF) and MongoDB. 
VM2 runs CHF only. 
![截圖 2024-05-07 上午11 39 24](https://github.com/free5gc/free5gc/assets/28786462/f34522da-c842-447d-9a17-6edfe9741e69)
